name: quizzical-deploy-template

on:
  workflow_call:

env:
  DOTNET_VERSION_10: "10.0.x"

jobs:
  build-deploy-quizzical-app:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: checkout code
        uses: actions/checkout@v4.1.1
      - name: setup dotnet
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION_10 }}
      - name: dotnet restore
        run: dotnet restore
        working-directory: ./src/Quizzical
      - name: run unit tests
        run: dotnet test ./tests/Quizzical.UnitTests/Quizzical.UnitTests.csproj --logger trx --results-directory ./tests/Quizzical.UnitTests/TestResults-${{ github.run_id }}-${{ github.run_attempt }}
      - name: publish unit test results
        uses: actions/upload-artifact@v4.3.1
        with:
          name: Quizzical.UnitTests
          path: ./tests/Quizzical.UnitTests/TestResults-${{ github.run_id }}-${{ github.run_attempt }}
      - name: build quizzical app
        run: dotnet publish ./src/Quizzical/Quizzical.csproj -c Release -o ./Publish/Quizzical
      - name: azure login
        uses: azure/login@v2.2.0
        with:
          creds: ${{ secrets.SERVICEPRINCIPAL }}
